---
- name: Create vault hosts
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create vault hosts
      add_host:
        name: "{{ item }}"
        groups: "{{ item }},vault_hosts"
        vault_env: "{{ item }}"
      with_items: "{{ env is defined | ternary([env], envs) | intersect(groups.keys()) }}"
      changed_when: false
      vars:
        envs: ['production','staging','development']

- name: General vault setup and create group_vars/all/vault.yml
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: vault }

- name: Create and process group_vars/<env>/vault.yml files
  hosts: vault_hosts
  connection: local
  gather_facts: false
  roles:
    - { role: vault }
