---
- name: General vault setup
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: vault }
  post_tasks:
    - name: Create dynamic vault hosts by environment
      add_host:
        name: "{{ item }}"
        groups: "{{ item }},vault_hosts"
        vault_env: "{{ item }}"
      with_items: "{{ env is defined | ternary([env], vault_groups) | intersect(groups.keys()) }}"
      changed_when: false

- name: Create and process group_vars/<env>/vault.yml files
  hosts: vault_hosts
  connection: local
  gather_facts: false
  roles:
    - { role: vault }
