---
- name: General vault setup
  include: setup-general.yml
  static: no
  when: vault_env is not defined

- name: Vault setup per environment
  include: setup-per-env.yml
  static: no
  when: vault_env is defined
